version: '3.8'

services:
  jupyter-server:
    build:
      context: .  # Use the Dockerfile in the current directory
    container_name: sparse-memory-container
    ports:
      - "8888:8888"
    volumes:
      - .:/app  # Mount current directory to /app in the container
    # The CMD from the Dockerfile will be used to start JupyterLab 